dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
  - pip install -e .[test]
script: pytest --cov=configpp --cov-report term --cov-report xml --cov-report annotate
after_success:
  coveralls
